modLoader = "javafml"
loaderVersion = "[4,)"
license = "Unlicense"

[[mods]]
modId = "shortcircuitfixtest"
version = "1"
displayName = "Short Circuit Fix client tests"
description = "Test-only assertions for Short Circuit Fix"

[[dependencies.shortcircuitfixtest]]
modId = "shortcircuitfix"
type = "required"
versionRange = "[1,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.shortcircuitfixtest]]
modId = "short_circuit"
type = "required"
versionRange = "[1,)"
ordering = "AFTER"
side = "CLIENT"
